# These are supported funding model platforms

open_collective: AncientBeast
patreon: FreezingMoon
custom: [paypal.me/AncientBeast, AncientBeast.com/contribute/#donate, bitcoin:1ALLZzy3AZGvAuNso4Wca8SCx9YGXJdFGb?label=Ancient%20Beast]
issuehunt: FreezingMoon/AncientBeast
ko_fi: DreadKnight
