# These are supported funding model platforms

open_collective: ancientbeast
patreon: FreezingMoon
custom: [bitcoin:1ALLZzy3AZGvAuNso4Wca8SCx9YGXJdFGb?label=Ancient%20Beast, paypal.me/AncientBeast, AncientBeast.com/contribute/#donate]
issuehunt: FreezingMoon/AncientBeast
ko_fi: dreadknight
