# These are supported funding model platforms

github: DreadKnight
patreon: FreezingMoon
open_collective: ancientbeast
ko_fi: dreadknight
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
issuehunt: dreadknight
custom: ['https://ancientbeast.com/contribute/#donate']
