# These are supported funding model platforms

open_collective: ancientbeast
patreon: FreezingMoon
custom: [paypal.me/AncientBeast, AncientBeast.com/contribute/#donate]
issuehunt: FreezingMoon/AncientBeast
ko_fi: dreadknight
