# These are supported funding model platforms

open_collective: ancientbeast
patreon: FreezingMoon
custom: ["bitcoin:1ALLZzy3AZGvAuNso4Wca8SCx9YGXJdFGb?label=Ancient%20Beast", "https://www.paypal.me/AncientBeast"]
issuehunt: FreezingMoon/AncientBeast
custom: https://ancientbeast.com/contribute/#donate
ko_fi: dreadknight
